#!/bin/bash

module load anaconda/3-4.2.0_cent


./tag-based_RNAseq/tagseq_clipper.pl C_HC_01.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o C_HC_01.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl C_HC_02.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o C_HC_02.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl C_HC_03.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o C_HC_03.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl C_HC_04.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o C_HC_04.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl C_HC_05.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o C_HC_05.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl C_HC_06.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o C_HC_06.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl C_HC_07.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o C_HC_07.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl C_HC_08.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o C_HC_08.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl C_HC_09.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o C_HC_09.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl C_HC_10.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o C_HC_10.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl C_LC_01.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o C_LC_01.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl C_LC_02.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o C_LC_02.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl C_LC_03.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o C_LC_03.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl C_LC_04.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o C_LC_04.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl C_LC_05.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o C_LC_05.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl C_LC_06.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o C_LC_06.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl C_LC_07.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o C_LC_07.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl C_LC_08.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o C_LC_08.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl C_LC_09.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o C_LC_09.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl C_LC_10.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o C_LC_10.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl HW_HC_01.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o HW_HC_01.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl HW_HC_02.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o HW_HC_02.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl HW_HC_03.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o HW_HC_03.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl HW_HC_04.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o HW_HC_04.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl HW_HC_05.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o HW_HC_05.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl HW_HC_06.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o HW_HC_06.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl HW_HC_07.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o HW_HC_07.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl HW_HC_08.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o HW_HC_08.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl HW_HC_09.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o HW_HC_09.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl HW_HC_10.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o HW_HC_10.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl HW_LC_01.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o HW_LC_01.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl HW_LC_02.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o HW_LC_02.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl HW_LC_03.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o HW_LC_03.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl HW_LC_04.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o HW_LC_04.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl HW_LC_05.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o HW_LC_05.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl HW_LC_06.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o HW_LC_06.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl HW_LC_07.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o HW_LC_07.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl HW_LC_08.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o HW_LC_08.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl HW_LC_09.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o HW_LC_09.fastq.trim
./tag-based_RNAseq/tagseq_clipper.pl HW_LC_10.fastq | cutadapt - -a AAAAAAAA -a AGATCGG -q 15 -m 25 -o HW_LC_10.fastq.trim
