#!/bin/sh

cat B1* > C_HC_02.fastq
cat C1* > C_HC_03.fastq
cat D1* > C_HC_04.fastq
cat E1* > C_HC_05.fastq
cat F1* > C_HC_06.fastq
cat G1* > C_HC_07.fastq
cat H1* > C_HC_08.fastq
cat A2* > C_HC_09.fastq
cat B2* > C_HC_10.fastq

cat C2* > C_LC_01.fastq
cat D2* > C_LC_02.fastq
cat E2* > C_LC_03.fastq
cat F2* > C_LC_04.fastq
cat G2* > C_LC_05.fastq
cat H2* > C_LC_06.fastq
cat A3* > C_LC_07.fastq
cat B3* > C_LC_08.fastq
cat C3* > C_LC_09.fastq
cat D3* > C_LC_10.fastq

cat E3* > HW_HC_01.fastq
cat F3* > HW_HC_02.fastq
cat G3* > HW_HC_03.fastq
cat H3* > HW_HC_04.fastq
cat A4* > HW_HC_05.fastq
cat B4* > HW_HC_06.fastq
cat C4* > HW_HC_07.fastq
cat D4* > HW_HC_08.fastq
cat E4* > HW_HC_09.fastq
cat F4* > HW_HC_10.fastq

cat G4* > HW_LC_01.fastq
cat H4* > HW_LC_02.fastq
cat A5* > HW_LC_03.fastq
cat B5* > HW_LC_04.fastq
cat C5* > HW_LC_05.fastq
cat D5* > HW_LC_06.fastq
cat E5* > HW_LC_07.fastq
cat F5* > HW_LC_08.fastq
cat G5* > HW_LC_09.fastq
cat H5* > HW_LC_10.fastq
