#! /bin/bash

module load fastqc/0.11.9

fastqc -o fastqc-files --noextract C_HC_01.fastq
fastqc -o fastqc-files --noextract C_HC_02.fastq
fastqc -o fastqc-files --noextract C_HC_03.fastq
fastqc -o fastqc-files --noextract C_HC_04.fastq
fastqc -o fastqc-files --noextract C_HC_05.fastq
fastqc -o fastqc-files --noextract C_HC_06.fastq
fastqc -o fastqc-files --noextract C_HC_07.fastq
fastqc -o fastqc-files --noextract C_HC_08.fastq
fastqc -o fastqc-files --noextract C_HC_09.fastq
fastqc -o fastqc-files --noextract C_HC_10.fastq
fastqc -o fastqc-files --noextract C_LC_01.fastq
fastqc -o fastqc-files --noextract C_LC_02.fastq
fastqc -o fastqc-files --noextract C_LC_03.fastq
fastqc -o fastqc-files --noextract C_LC_04.fastq
fastqc -o fastqc-files --noextract C_LC_05.fastq
fastqc -o fastqc-files --noextract C_LC_06.fastq
fastqc -o fastqc-files --noextract C_LC_07.fastq
fastqc -o fastqc-files --noextract C_LC_08.fastq
fastqc -o fastqc-files --noextract C_LC_09.fastq
fastqc -o fastqc-files --noextract C_LC_10.fastq
fastqc -o fastqc-files --noextract HW_HC_01.fastq
fastqc -o fastqc-files --noextract HW_HC_02.fastq
fastqc -o fastqc-files --noextract HW_HC_03.fastq
fastqc -o fastqc-files --noextract HW_HC_04.fastq
fastqc -o fastqc-files --noextract HW_HC_05.fastq
fastqc -o fastqc-files --noextract HW_HC_06.fastq
fastqc -o fastqc-files --noextract HW_HC_07.fastq
fastqc -o fastqc-files --noextract HW_HC_08.fastq
fastqc -o fastqc-files --noextract HW_HC_09.fastq
fastqc -o fastqc-files --noextract HW_HC_10.fastq
fastqc -o fastqc-files --noextract HW_LC_01.fastq
fastqc -o fastqc-files --noextract HW_LC_02.fastq
fastqc -o fastqc-files --noextract HW_LC_03.fastq
fastqc -o fastqc-files --noextract HW_LC_04.fastq
fastqc -o fastqc-files --noextract HW_LC_05.fastq
fastqc -o fastqc-files --noextract HW_LC_06.fastq
fastqc -o fastqc-files --noextract HW_LC_07.fastq
fastqc -o fastqc-files --noextract HW_LC_08.fastq
fastqc -o fastqc-files --noextract HW_LC_09.fastq
fastqc -o fastqc-files --noextract HW_LC_10.fastq
